FROM node:12-alpine
# RUN apk add --no-cache python g++ make
WORKDIR /front
COPY package*.json .
# RUN apk --no-cache --virtual build-dependencies add \
#         python \
#         make \
#         g++
RUN npm install
COPY . .
EXPOSE 3000