FROM node:12
# RUN apk add --no-cache g++ python make
WORKDIR /front
COPY package*.json .
# RUN apk --no-cache --virtual build-dependencies add \
#         python \
#         make \
#         g++
RUN npm install
COPY . .
EXPOSE 3000 