version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=mydb
      - MARIADB_PASSWORD=my_password
    volumes :
      - ./mariadb_data:/bitnami/mariadb  
    ports:
      - 3306:3306
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=mydb
      - DB_PASSWORD=
    depends_on:
      - mariadb
    ports:
      - 8000:3000
    volumes:
      - ./:/app
    privileged: true # Privileged mode could be required to run this container under Windows